[package]
name = "test_project"
version = "0.1.0"
authors = ["keaysma <michaelandrewkeays@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.3.14"
rustyline = "5.0.4"
